### PR TITLE
Fix typo in server url variable

### PR DESCRIPTION
**Pull request by guilhermecomum**
Just a typo in the readme.
Thank you so much for this package!

### CODE REVIEW

**Comment by PillFall** [comment]
Great, @guilhermecomum thanks for noticing that out.

As I mentioned in another pull requests, I follow git flow, so all pull requests should be made for merging onto develop branch.

**Comment by PillFall** [comment]
I must upload a contributing guideline, sorry for that 😓

**Review by PillFall — CHANGES_REQUESTED** [review]
I don't want to fix it by myself as you will lose the contributing mark.

Can you please redo the pull request?

**Comment by guilhermecomum** [comment]
Sorry the delay, it's correct now?

**Comment by PillFall** [comment]
No, I think you must redo the pull request as GitHub mess the requests. Trying to merge release commits.

**Comment by PillFall** [comment]
This is almost half a year old now. As I'm getting no response, I fix the issue myself and close the merge request.

**Pull request closed without merging**
